name: CI

on:
  push:
    branches:
      - pepecoin
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Run cargo check --all-targets
      run: cargo check --all-targets

  test:
    runs-on: ubuntu-22.04
    steps:
    - run: sudo apt-get update && sudo apt-get install libfuse2
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Run tests (REST+Electrum)
      run: RUST_LOG=debug cargo test

  test-electrum-raw:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Run test test_electrum_raw
      run: RUST_LOG=debug cargo test -- --include-ignored test_electrum_raw

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .

  release:
    name: Release Binary
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake clang
      - name: Build
        run: cargo build --release --bin electrs
      - name: Package
        shell: bash
        run: |
          cd target/release
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            tar -czf electrs-pepe-linux.tar.gz electrs
          else
            tar -czf electrs-pepe-macos.tar.gz electrs
          fi
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/electrs-pepe-linux.tar.gz
            target/release/electrs-pepe-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
